### ISSUE TITLE
Cannot find shared library for language: r

### ISSUE THREAD

**Issue by zhenhua-wang** [ShuguangSun/tree-sitter-ess-r#1]
Thank you for this package! I am getting this error while install it. `tree-sitter-ess-r/:catch: Cannot find shared library for language: r`. Do you know how to fix this? I have `tree-sitter` and `tree-sitter-langs` installed.

**Comment by ShuguangSun** [comment]
r is not included in the tree-sitter package and we need to compile it. Please refer to https://github.com/manateelazycat/grammatical-edit
