### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by mguzmann** [ShuguangSun/tree-sitter-ess-r#4]
I followed the instructions but the highlighting seems to not be doing anything.
There are no errors but there is also nothing happening. At least I don't get anything.

If I understand treesitter correctly, the variable `tree-sitter-hl-default-patterns` must be set to [something](https://emacs-tree-sitter.github.io/syntax-highlighting/interface-for-modes/).
But this mod does not seem to set it.
Am I wrong here?

**Comment by ShuguangSun** [comment]
Do you have the most updated `tree-sitter-langs` installed? It ships the `r` things and we don't need to compile the tree-sitter-r mannully. 

If you don't have verion 20221126 of `tree-sitter-langs` installed, do you have tree-sitter-r's r.dll or r.so?

**Comment by mguzmann** [comment]
Yes, I have 20221126.446. Other tree-sitter packages like ts-fold work fine with R. r.so is in the language library.

**Comment by ShuguangSun** [comment]
How about call `tree-sitter-ess-r-using-r-faces`?

The `tree-sitter-hl-default-patterns` is set to the content of `highlights.scm` in the `tree-sitter-langs-20221126.446/queries/r`. If it is not, there is something wrong with `tree-sitter-langs`. 
Actually, if the `tree-sitter-ess-r` is not loaded, the `tree-sitter-hl-mode` will handle r as other supported languages.  `tree-sitter-ess-r` just makes the highlights like ess-r.

**Comment by mguzmann** [comment]
Ok, I must have made a mistake because the file was called `highlight.scm` and tree-sitter couldn't find it. Thanks.
